load("//:defs.bzl", "create_cc_tests")

test_names = [
    "avl_tree_test",
    "bloom_filter_test",
    "btree_test",
    "bucket_test",
    "buffer_pool_test",
    "extensible_hashtable_test",
    "kv_store_test",
    "lru_test",
]

create_cc_tests(test_names=test_names)
