cc_library(
  name="test_utils",
  srcs=["test_utils.cpp", "test_utils.hpp"],
  # includes=["//include"],
  deps=[
    # "//include:headers",
    "//src:kv_store_lib",
  ],
  visibility=["//visibility:public"],
)
